### ISSUE TITLE
Running a subcommand without the actual subcommand crashes

### ISSUE THREAD

**Issue by mybearworld** [NanderTGA/msgroom-orm#55]
If you have subcommands like `!a b`, `!a c`, `!a d`, just trying to call `!a` crashes msgroom-nightly. Here's the error from toB:

```js
<toBPath>\node_modules\msgroom-nightly\dist\index.js:281
                    if (key.toLowerCase() == command.toLowerCase()) {
                                                     ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Client.getCommand (<toBPath>\node_modules\msgroom-nightly\dist\index.js:281:54)
    at Client.processCommands (<toBPath>\node_modules\msgroom-nightly\dist\index.js:317:42)
    at Socket.<anonymous> (<toBPath>\node_modules\msgroom-nightly\dist\index.js:136:27)
    at Emitter.emit (<toBPath>\node_modules\@socket.io\component-emitter\index.js:143:20)
    at Socket.emitEvent (<toBPath>\node_modules\socket.io-client\build\cjs\socket.js:519:20)
    at Socket.onevent (<toBPath>\node_modules\socket.io-client\build\cjs\socket.js:506:18)
    at Socket.onpacket (<toBPath>\node_modules\socket.io-client\build\cjs\socket.js:474:22)
    at Emitter.emit (<toBPath>\node_modules\@socket.io\component-emitter\index.js:143:20)
    at <toBPath>\node_modules\socket.io-client\build\cjs\manager.js:237:18
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.16.0
```

**Comment by NanderTGA** [comment]
Does a.undefined exist?

**Comment by mybearworld** [comment]
What do you mean? I have not specified an `undefined` property on the object.

**Comment by NanderTGA** [comment]
When you execute `!a`, it will actually call `!a undefined`

**Comment by NanderTGA** [comment]
Every commandMap is expected to have this property (except client.commands).
I need to add some checks for this maybe.

**Comment by mybearworld** [comment]
> I tested your code and you need to add the `undefined` property to make it stop crashing, like this: ![afbeelding](https://user-images.githubusercontent.com/65074195/253332846-ff7cd6cd-8a1b-4697-91c9-b151cc78691b.png)

Okay, thank you, I wasn't aware of this - in earlier versions, it would just not do anything.

**Comment by NanderTGA** [comment]
The undefined commands are a giant mess, my apologies for that.
#43 will fix this, and I'll add a note somewhere to check if the handler property actually exists, incase someone would forget somehow. I'll use this issue as that note.

**Comment by NanderTGA** [comment]
This confusion will not happen anymore with the new metadata for (sub)commands system, see #43.
